### ISSUE TITLE
Feature planning

### ISSUE THREAD

**Issue by rdig** [JoinColony/purser#30]
This PR is here to track planned features, as well as to track new proposals. Just add comments.

### Needed features:

- [ ] Hardware wallet support: Trezor
- [ ] Hardware wallet support: Digital bitbox
- [ ] Hardware wallet support: Ledger Nano S
- [ ] Browser extension support: Metamask
- [ ] Software wallet expose _(with docs)_ basic transaction methods _(eg: `sign()`, `sendTransaction()`)_ #26 
- [x] Software wallet `signWithPrompt()` method. Done in #32 

### Maintenance

- [ ] Rename `localhost()` provider method #34 

### Feature proposals:

- [ ] Custom token balances _(something like: `balanceOfToken('tokenName', 18)`, keep a registry of well-known tokens, and have a way to "register" new ones)_
