### ISSUE TITLE
Rename `localhost` provider method

### ISSUE THREAD

**Issue by rdig** [JoinColony/purser#34]
In not one of my proudest moments, I've named the method that connects to a `json-rpc` service as `localhost()`.

In retrospect this name choice is very poor and should be remedied. 

Firstly because it's confusing and secondly because you can connect to `json-rpc` server that is **not** hosted on your local machine...

Good names alternatives: `jsonRPC()` or `jsonRpc()`.

### TODO

- [ ] Rename method in `providers.js`
- [ ] Change method name in providers `autoselect()` method
- [ ] Change method name in unit tests
- [ ] Change method name in documentation _(`docs/api.md`)_
